//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot.Localization.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bot.Localization.Languages.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account deleted successfully.
        /// </summary>
        internal static string AccountDeletedSuccessfully {
            get {
                return ResourceManager.GetString("AccountDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding a machine.
        /// </summary>
        internal static string AddingError {
            get {
                return ResourceManager.GetString("AddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new machine.
        /// </summary>
        internal static string AddNewMachine {
            get {
                return ResourceManager.GetString("AddNewMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user with this name is already registered.
        /// </summary>
        internal static string AlreadyRegistered {
            get {
                return ResourceManager.GetString("AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have canceled the action.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose language.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a directory.
        /// </summary>
        internal static string CreateDirectory {
            get {
                return ResourceManager.GetString("CreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete your account.
        /// </summary>
        internal static string DeleteAccount {
            get {
                return ResourceManager.GetString("DeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete a directory.
        /// </summary>
        internal static string DeleteDirectory {
            get {
                return ResourceManager.GetString("DeleteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download the file.
        /// </summary>
        internal static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🇬🇧 English.
        /// </summary>
        internal static string En {
            get {
                return ResourceManager.GetString("En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute commands.
        /// </summary>
        internal static string ExecuteCommands {
            get {
                return ResourceManager.GetString("ExecuteCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello! I&apos;m here to help you interact with your virtual machines.
        /// </summary>
        internal static string HelloMessage {
            get {
                return ResourceManager.GetString("HelloMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input account password.
        /// </summary>
        internal static string InputAccountPassword {
            get {
                return ResourceManager.GetString("InputAccountPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the command.
        /// </summary>
        internal static string InputCommand {
            get {
                return ResourceManager.GetString("InputCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the directory.
        /// </summary>
        internal static string InputDirectoryName {
            get {
                return ResourceManager.GetString("InputDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        internal static string InputEmail {
            get {
                return ResourceManager.GetString("InputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send the file you want to upload.
        /// </summary>
        internal static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the path to the file.
        /// </summary>
        internal static string InputFilePath {
            get {
                return ResourceManager.GetString("InputFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a password.
        /// </summary>
        internal static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create username.
        /// </summary>
        internal static string InputUserName {
            get {
                return ResourceManager.GetString("InputUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the virtual machine host.
        /// </summary>
        internal static string InputVMHost {
            get {
                return ResourceManager.GetString("InputVMHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the virtual machine.
        /// </summary>
        internal static string InputVMName {
            get {
                return ResourceManager.GetString("InputVMName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the virtual machine port.
        /// </summary>
        internal static string InputVMPort {
            get {
                return ResourceManager.GetString("InputVMPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the username on the virtual machine.
        /// </summary>
        internal static string InputVMUser {
            get {
                return ResourceManager.GetString("InputVMUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the user password on the virtual machine.
        /// </summary>
        internal static string InputVMUserPassword {
            get {
                return ResourceManager.GetString("InputVMUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid resource key.
        /// </summary>
        internal static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged out.
        /// </summary>
        internal static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to your account.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        internal static string LoginPassword {
            get {
                return ResourceManager.GetString("LoginPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username.
        /// </summary>
        internal static string LoginUserName {
            get {
                return ResourceManager.GetString("LoginUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out of your account.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        internal static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw data.
        /// </summary>
        internal static string RawData {
            get {
                return ResourceManager.GetString("RawData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create an account.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select account to delete.
        /// </summary>
        internal static string SelectAccountToDelete {
            get {
                return ResourceManager.GetString("SelectAccountToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual machine added successfully.
        /// </summary>
        internal static string SuccessesAdd {
            get {
                return ResourceManager.GetString("SuccessesAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language successfully changed.
        /// </summary>
        internal static string SuccessesChange {
            get {
                return ResourceManager.GetString("SuccessesChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully logged in.
        /// </summary>
        internal static string SuccessesLogin {
            get {
                return ResourceManager.GetString("SuccessesLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully registered.
        /// </summary>
        internal static string SuccessesRegister {
            get {
                return ResourceManager.GetString("SuccessesRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ToCancel {
            get {
                return ResourceManager.GetString("ToCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload the file.
        /// </summary>
        internal static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected a virtual machine for interaction.
        /// </summary>
        internal static string VMChosen {
            get {
                return ResourceManager.GetString("VMChosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any registered accounts.
        /// </summary>
        internal static string YouDontHaveAccounts {
            get {
                return ResourceManager.GetString("YouDontHaveAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to log in to the system.
        /// </summary>
        internal static string YouHaveToLogin {
            get {
                return ResourceManager.GetString("YouHaveToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your accounts.
        /// </summary>
        internal static string YourAccounts {
            get {
                return ResourceManager.GetString("YourAccounts", resourceCulture);
            }
        }
    }
}
