version: '3.9'

services:
    sql-server-db:
        image: mcr.microsoft.com/mssql/server
        container_name: sql-server-db
        restart: always
        environment:
            - MSSQL_SA_PASSWORD=Strong2@PWD12
            - ACCEPT_EULA=Y
        ports:
            - "5434:1433"
        volumes:
            - sqlvolume:/var/opt/mssql
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
          - "6379:6379"
        volumes:
          - /path/to/local/data:/root/redis
          - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
          - REDIS_PORT=6379

volumes:
    sqlvolume: